name: MCZJUGameCore
version: '${project.version}'
main: com.github.mczjuops.mczjugamecore.MCZJUGameCore
api-version: '26.2'
softdepend:
  - Multiverse-Core
commands:
  mgc:
    description: "小游戏基础命令"
    permission: mgc.mgc
  party:
    description: "组队系统命令"
    permission: mgc.party
  menu:
    description: "打开部分MCZJUGameCore或子插件的菜单"
    permission: menu.op
  mgcop:
    description: "MCZJUGameCore管理员命令"
    permission: mgc.dev
  lobby:
    description: "传送到主大厅或小游戏等待大厅"
    aliases: [l]
    permission: mgc.lobby


permissions:
  mgc.mgc:
    default: true
  mgc.party:
    default: true
  mgc.lobby:
    default: true
  mgc.dev:
    default: op
  menu.default:
    default: true
  menu.op:
    default: op
